# Launch : docker-compose up --build
# Quand on a fait l'upload de build, on doit juste migrer la base de donnee pour la mise a jour: docker-compose exec server npm run db:migrate

# Stop : docker-compose down
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skillsync_db
    ports:
      - "3306:3306"

  server:
    build: ./server
    ports:
      - "3310:3310"
    environment:
      APP_SECRET: secretkeygenerated123456!#@
      CLIENT_URL: http://localhost:3000
      APP_PORT: 3310
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: skillsync_db
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:3310/api
    depends_on:
      - server
